version: '3.8'

services:
  app:
    build: .
    container_name: mi_app_laravel
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
