global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'laravel'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['192.168.1.247:8000']
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.247:8083']
  - job_name: 'orden-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.247:8084']
